language: node_js
node_js:
  - stable
addons:
  sonarcloud:
    organization: "nandhu08-github"
    token:
      secure: "9ebdb1592d22f6f5fb115bdcc293cad820f0c611"
  sauce_connect:
    username: "nandhu08"
    access_key: "176cb8ec-c9e3-49e5-963d-ea77825cf4fb"
script:
  - sonar-scanner
  - npm run build  
  - npm test